version: '3'
services:
  app:
    build:
      context: .
      dockerfile: env/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8800-8899:8888"
      - "5000-5099:5000"

#    runtime: nvidia
